### ISSUE TITLE
No Prisoners Secondary Count Includes Monsters

### ISSUE THREAD

**Issue by MikeEmery** [maybe-hello-world/40k-roster-formatter#46]
Thanks for adding the secondaries.

I noticed it's including monsters in the total, no prisoners should exclude `monster`, `vehicle`, and `character`. 

![image](https://user-images.githubusercontent.com/333088/178488174-3f411b1f-dd53-4f7c-aa2e-cfcf90161408.png)

**Comment by maybe-hello-world** [comment]
I cannot reproduce this error. Could you please send me the roster file?

**Comment by maybe-hello-world** [comment]
Please, ensure that you have the last version of bsdata. Sometimes bugs and missing keywords are fixed rather late :)

**Comment by MikeEmery** [comment]
I've attached the roster file zipped.  I tried updating the data but I still see the same thing, not sure if I would need to change the list at all to get it to pick up changes.  I do see `Monster` as a keyword when I look at the screamer killer in battlescribe.

[Kraken nephilim.zip](https://github.com/maybe-hello-world/40k-roster-formatter/files/9096411/Kraken.nephilim.zip)
